"""remove email from users

Revision ID: 5aa73674ce67
Revises: 735e751c4aaa
Create Date: 2024-09-07 18:39:36.698491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa73674ce67'
down_revision: Union[str, None] = '735e751c4aaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=False))
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    # ### end Alembic commands ###
